name: nwbdj
channels:
- defaults
- conda-forge
- edeno
- franklab
dependencies:
- "python==3.6"
- matplotlib
- pandas
- networkx
- datajoint
- python-dateutil
- ipywidgets
- nodejs
- jupyter
- jupyterlab
- nb_conda
- tqdm
- setuptools
- pytest
- pytest-cov
- coveralls
- pynwb
- pybind11
- distributed
- pip
- pip:
  - python-intervals
  - ghostipy
  - spikeinterface
  - kachery==0.6.4
