name: nwb_datajoint_test
channels:
- defaults
- conda-forge
- edeno
- franklab
dependencies:
- "python>=3.6"
- pynwb
- matplotlib
- pandas
- networkx
- datajoint
- python-dateutil
- ipywidgets
- nodejs
- jupyter
- jupyterlab
- nb_conda
- tqdm
- setuptools
- pytest
- pytest-cov
- coveralls
- ghostipy
- pip
- pip:
  - python-intervals
<<<<<<< HEAD
=======
  - ghostipy
  - spikeinterface
>>>>>>> develop_nwbraw
