name: Black Formatter
on: [push, pull_request]
jobs:
  black-format:
    runs-on: ubuntu-latest
    steps:
      - uses: Ahuge/black-action@v1.0.3
      - name: Black Code Formatter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BLACK_ARGS: "."
